# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

# Site settings
title: Shared Trading
email: support@thesharedtrading.com
description: >- # this means to ignore newlines until "baseurl:"
  Shared Trading offers indicators which allow order duplications between
  different account and different platforms, such as NinjaTrader or Metatrader.
author: Shared Trading Team
baseurl: "" # the subpath
url: "https://thesharedtrading.com" # the base hostname & protocol

# Social Profiles
twitter_username:   SharedTradingES
github_username:    thesharedtrading
facebook_username:  
instagram_username: 
linkedin_username:  

# Header
header_pages:
  - "index.md"
  - "posts/index.html"
  - "contact.html"
  - "ninjatrader.html"

# Comments
disqus:
  shortname: thesharedtrading

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-HXHFK77MJY

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

exclude:
  - CNAME
  - README.md
  - .gitignore
